language: php

php:
    - 7.0
    - 5.6
    - 5.5

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true

    - composer self-update

install:
    - composer update --prefer-dist ${COMPOSER_FLAGS}

script:
    - composer validate --strict

    - vendor/bin/phpspec run -f pretty
